Fix backend: Add missing bs58 dependency for @coinbase/cdp-sdk
The backend was failing to start with:
Error: Cannot find module 'bs58'

This is a peer dependency required by @coinbase/cdp-sdk
used in x402PaymentService.